---
- name: Secret file for Panda
  template:
    src: secret.j2
    dest: /home/opc/ansible/secret.yml
    mode: 0600

# - name: Debug hostvars
#   debug:
#     msg: "Var host {{hostvars}}"

- name: Hosts file for Panda
  template:
    src: hosts.j2
    dest: /home/opc/ansible/hosts.yml
    mode: 0660

- name: Copy pem file
  copy:
    src: "~/.oci/oci_api_key.pem"
    dest: /home/opc/.oci/oci_api_key.pem
    mode: 0600

- name: Create ssh key
  command: ssh-keygen -t rsa -N "" -b 2048  ~/.ssh/id_rsa
  args: 
      chdir: ~/.ssh
      creates: ~/.ssh/id_rsa
  delegate_to: 127.0.0.1

- name: Copy ssh key
  copy:
    src: "~/.ssh/id_rsa"
    dest: /home/opc/.ssh/private_key
    mode: 0600

- name: Create aliases
  blockinfile:
    path: /home/opc/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      alias mig-srv-setup="opcmigrate migrate instance service setup"
      alias mig-srv-start="opcmigrate migrate instance service start"
      alias mig-srv-stop="opcmigrate migrate instance service stop"
      alias mig-src-setup="opcmigrate migrate instance source setup"
      alias mig-srv-status="opcmigrate migrate instance service status"
      alias mig-ctlt-setup="opcmigrate migrate instance ctlt setup"
      alias mig-job-run="opcmigrate migrate instance job run"
      alias mig-job-list="opcmigrate migrate instance job list"
      alias mig-job-status="opcmigrate migrate instance job status"
      alias mig-job-resume="opcmigrate migrate instance job resume"
      alias mig-job-delete="opcmigrate migrate instance job delete"
      alias mig-discover="opcmigrate discover"
      alias mig-plan="opcmigrate plan create --output migration-plan.json"
      alias mig-instances="opcmigrate instances-export --plan migration-plan.json --format json > instances.json"
      alias mig-volumes="jq '.storage_volume | .[] | .name' migration-plan.json"
      alias mig-job-details="~/mig status | tail -n +2 | jq '.[length-1].instances[] | .start_time, .update_time, .src_instance_name, .volumes[].status_details'"
