---
- name: Clean Migrate directory
  become: yes
  become_user: root
  file:
    path: "{{dbmig.migrate_dir}}"
    state: absent

- name: Create Migrate directory
  file:
    path: "{{dbmig.migrate_dir}}"
    state: "directory"

- name: Unzip opc_installer
  unarchive:
    src: "opc_installer.zip"
    dest: "{{dbmig.migrate_dir}}"
    copy: yes

- name: Config file for OCI CLI
  template:
    src: config.j2
    dest: "{{dbmig.migrate_dir}}/config.txt"
    mode: 0600

- name: DB backup script
  template:
    src: backup.j2
    dest: "{{dbmig.migrate_dir}}/backup.sh"
    mode: 0775

- name: Copy pem file
  copy:
    src: "~/.oci/oci_api_key.pem"
    dest: "{{dbmig.migrate_dir}}"
    mode: 0600

# - name: Copy yum repo
#   copy:
#     src: "yum-phx-ol6.repo"
#     dest: /etc/yum.repos.d/yum-phx-ol6.repo
#     mode: 0664

- name: Install Python dependencies
  become: yes
  become_user: root
  yum:
    state: latest
    name:
      - gcc
      - libffi-devel
      - python-devel
      - openssl-devel

# Esse export é necessario para que o cli seja instalado no diretorio
# do user oracle. Isso é necessário pois o script de instalação invoca sudo
# e precisa ser executado pelo root
- name: Install OCI CLI on oracle
  become: true
  become_user: root
  raw: cd;export HOME={{dbmig.migrate_dir}};bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh) --accept-all-defaults --optional-features 'db'"

- name: Change oracle dir owner
  become: true
  become_user: root
  file:
    dest: "/home/oracle"
    owner: oracle
    group: oinstall
    recurse: yes

- name: Start Database backup async
  shell: "{{dbmig.migrate_dir}}/backup.sh"
  async: 300000
  poll: 15

# - name: Install OCI CLI
#   become: true
#   become_user: root
#   expect:
#     chdir: "/root"
#     echo: yes
#     command: install.sh
#     responses:
#        (.*)Missing native dependencies(.*): "Y"
#        (.*)install(.*): "{{dbmig.migrate_dir}}/lib/oracle-cli"
#        (.*)executable(.*): "{{dbmig.migrate_dir}}/bin"
#        (.*)scripts(.*): "{{dbmig.migrate_dir}}/bin/oci-cli-scripts"
#        (.*)optional packages(.*): "db"
#        (.*)tab completion now(.*): "Y"
#        (.*)rc file to update(.*): "/home/oracle/.bashrc"
#     timeout: 600
