---
# tasks file for win.source

- name: Copy Windows license verifier
  win_copy:
    src: windows_migrate.ps1
    dest: C:\

- win_shell: C:\windows_migrate.ps1
  register: lic

- name: Debug license
  debug:
    msg: "{{lic.stdout_lines}}"