---
- name: Create .ssh directory
  file:
    path: "~/.ssh"
    state: "directory"

- name: Create .oci dir
  file:
    path: "~/.oci"
    state: "directory"

- name: Create ssh key
  command: ssh-keygen -t rsa -N "" -b 2048 -f id_rsa
  args:
    chdir: ~/.ssh
    creates: ~/.ssh/id_rsa
  delegate_to: 127.0.0.1

- name: Create API signing key
  command: openssl genrsa -out oci_api_key.pem 2048
  args:
    chdir: ~/.oci
    creates: ~/.oci/oci_api_key.pem
  delegate_to: 127.0.0.1


- name: Create API public key
  command: openssl rsa -pubout -in oci_api_key.pem -out oci_api_key_public.pem
  args:
    chdir: ~/.oci
    creates: ~/.oci/oci_api_key_public.pem
  delegate_to: 127.0.0.1
